name: "actions-git"
description: "Helper actions for working with git on github actions"
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
inputs:
  myInput:
    description: "Dummy input value"
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs
outputs:
runs:
  using: "node12"
  main: "index.js"
