name: main
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: self-hosted
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: "npm"

      - name: 📥 Download deps
        run: npm install

      - name: ▶️ Run validate script
        run: npm run validate

  release:
    runs-on: self-hosted
    needs: [build]
    # Run on non-fork branches only (master/main)
    if: ${{ !github.event.fork && !contains(github.ref, 'pull') }}
    steps:
      - uses: actions/checkout@v2
      - uses: tradeshift/actions-semantic-release@v1
        id: semantic-release
        with:
          branches: |
            [
              'master'
            ]
          check_name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Action tags (major version tag)
        if: ${{ steps.semantic-release.outputs.new_release_published }}
        run: |
          git tag -f v${{ steps.semantic-release.outputs.new_release_major_version }}
          git push -f origin v${{ steps.semantic-release.outputs.new_release_major_version }}
